config/routes.rb
Rails.application.routes.draw do
  get '/orders/track_order', to: 'orders#track_order'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
  end
  resources :orders
  resources :tenants
  root 'orders#index'

  get '/auth/:provider/callback', to: 'users#update_twitter_tokens'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      post 'send_message' => 'orders/send_message'
    end
  end

end

app/models/tenant.rb
class Tenant < ActiveRecord::Base
 has_many :users
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  def new
    @tenant = Tenant.new
  end

  def create
    @tenant = Tenant.new(tenant_params)
    @tenant.save
    redirect_to root_path
  end

  private
  def tenant_params
    params.require(:tenant).permit(:name, :subdomain, :company_email, :company_phone, :password, :confirm_password)
  end
end

app/views/tenants/_form.html.erb
<div class="container">
<%= form_for :tenant, url: tenants_path do |f| %>
  <div class="col-md-6">
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control required', required: true %>
  </p>
 
 <p>
    <%= f.label :subdomain %><br>
    <%= f.text_field :subdomain, class: 'form-control required', required: true %>
  </p>
 
 <p>
    <%= f.label :company_email %><br>
    <%= f.text_field :company_email, class: 'form-control required', required: true %>
  </p>
 
 <p>
    <%= f.label :company_phone %><br>
    <%= f.text_field :company_phone, class: 'form-control required', required: true %>
  </p>
 
 <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, class: 'form-control required', required: true %>
  </p>
 
  <p>
    <%= f.label :confirm_password %><br>
    <%= f.password_field :confirm_password, class: 'form-control required', required: true %>
  </p>
 
  <p>
    <%= f.submit 'Add Tenant', class: 'btn btn-primary' %>
  </p>
  </div>
<% end %>
</div>

app/views/tenants/new.html.erb
<%= render 'form' %>