config/routes.rb
Rails.application.routes.draw do
  get '/orders/track_order', to: 'orders#track_order'
  
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  devise_scope :user do
    get 'sign_in', to: 'users/sessions#new'
  end
  resources :orders
  resources :tenants
  root 'orders#index'

  get '/auth/:provider/callback', to: 'users#update_twitter_tokens'

  mount Sidekiq::Web, at: '/sidekiq'

  namespace :api do
    namespace :v1 do
      post 'send_message' => 'orders/send_message'
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
 <html>
 <head>
   <title>Socommerce Rails</title>
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
   <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
   <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
   <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
   <%= csrf_meta_tags %>
 </head>
 <body>
 
 <nav class="navbar navbar-inverse">
   <div class="container">
     <div class="navbar-header">
       <%= link_to 'Socommerce', root_path, class: 'navbar-brand' %>
     </div>
     <div id="navbar">
       <ul class="nav navbar-nav">
         <li><%= link_to 'Home', root_path %></li>
       </ul>
       <ul class="nav navbar-nav pull-right">
         <% if user_signed_in? %>
           <li class="dropdown">
             <a class="dropdown-toggle" data-toggle="dropdown" href="#">
               <%= current_user.email %>
               <span class="caret"></span>
             </a>
             <ul class="dropdown-menu" role="menu">
               <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
             </ul>
           </li>
         <% else %>
           <li><%= link_to 'Orders', orders_path %></li>
           <li><%= link_to 'Log In', new_user_session_path %></li>
           <li><%= link_to 'SignUp', new_tenant_path %></li>
         <% end %>
       </ul>
     </div>
   </div>
 </nav>
 
 <% if !user_signed_in? %>
 <div class="jumbotron">
     <div class="container">
       <h1>Welcome!</h1>
       <p>Register to get started.</p>
       <p>
         <%= link_to 'Register', '/users/sign_up', class: 'btn btn-primary btn-lg' %>
       </p>
     </div>
   </div>
<% elsif !current_user.twitter_id.present?%>

  <div class="jumbotron">
     <div class="container">
       <p>Authenticate your twitter to get started.</p>
       <p>
         <%= link_to 'Authenticate', '/auth/twitter', class: 'btn btn-primary btn-lg' %>
       </p>
     </div>
   </div>
<% end %>
 
 <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>

 <%= yield %>

 <div id="footer">
  <div class="container">
    <p class="text-muted">Created by <a href="#" target="_blank">SoCommerce</a></p>
</div>
</div>
 
 </body>
 </html>